// flow-typed signature: 4cb0e2bec551909a5367d0e1b6198973
// flow-typed version: <<STUB>>/eslint-config-precure_v^2.7.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-precure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-precure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-precure/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/import/index' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/jest' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/oss' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/react' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/stylistic' {
  declare module.exports: any;
}

declare module 'eslint-config-precure/unicorn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-precure/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-precure/best-practices'>;
}
declare module 'eslint-config-precure/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-precure/flowtype'>;
}
declare module 'eslint-config-precure/import/index.js' {
  declare module.exports: $Exports<'eslint-config-precure/import/index'>;
}
declare module 'eslint-config-precure/index' {
  declare module.exports: $Exports<'eslint-config-precure'>;
}
declare module 'eslint-config-precure/index.js' {
  declare module.exports: $Exports<'eslint-config-precure'>;
}
declare module 'eslint-config-precure/jest.js' {
  declare module.exports: $Exports<'eslint-config-precure/jest'>;
}
declare module 'eslint-config-precure/oss.js' {
  declare module.exports: $Exports<'eslint-config-precure/oss'>;
}
declare module 'eslint-config-precure/possible-errors.js' {
  declare module.exports: $Exports<'eslint-config-precure/possible-errors'>;
}
declare module 'eslint-config-precure/react.js' {
  declare module.exports: $Exports<'eslint-config-precure/react'>;
}
declare module 'eslint-config-precure/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-precure/stylistic'>;
}
declare module 'eslint-config-precure/unicorn.js' {
  declare module.exports: $Exports<'eslint-config-precure/unicorn'>;
}
